import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./global.module.scss";
import Navbar from "./Components/navbar/navbar";
import Footer from "./Components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className={styles.header_wrapper}></div>
      <Navbar />
        {children}
      <Footer />
      </body>
    </html>
  );
}
